mesos-master:
  image: bcrusu/mesosdev:latest
  entrypoint: mesos-master
  command: --cluster=playground --port=5050 --registry=in_memory --quorum=1 --log_dir=/cluster/master
  net: "host"
  volumes:
   - ./cluster:/cluster
  environment:
   - LIBPROCESS_IP=10.0.0.33

mesos-slave1:
  image: bcrusu/mesosdev:latest
  entrypoint: mesos-slave
  command: --master=10.0.0.33:5050 --port=5051 --resources='cpus:2;mem:512' --log_dir=/cluster/slave1
  net: "host"
  volumes:
   - ./cluster:/cluster
  environment:
   - LIBPROCESS_IP=10.0.0.33

mesos-slave2:
  image: bcrusu/mesosdev:latest
  entrypoint: mesos-slave
  command: --master=10.0.0.33:5050 --port=5052 --resources='cpus:2;mem:512' --log_dir=/cluster/slave2
  net: "host"
  volumes:
   - ./cluster:/cluster
  environment:
   - LIBPROCESS_IP=10.0.0.33

mesos-slave3:
  image: bcrusu/mesosdev:latest
  entrypoint: mesos-slave
  command: --master=10.0.0.33:5050 --port=5053 --resources='cpus:2;mem:512' --log_dir=/cluster/slave3
  net: "host"
  volumes:
   - ./cluster:/cluster
  environment:
   - LIBPROCESS_IP=10.0.0.33
